### ISSUE TITLE
Cant execute __main__.py

### ISSUE THREAD

**Issue by mustardbutter** [alexeyNaidiuk/ProxyScraperChecker#1]
C:\Users\Professional\proxy_parser\proxy_parser>python __main__.py
Traceback (most recent call last):
  File "C:\Users\Professional\proxy_parser\proxy_parser\__main__.py", line 5, in <module>
    from proxy_parser.checkers import check_proxies_generator
ModuleNotFoundError: No module named 'proxy_parser'

Здесь играют без ошибок братанчик)))

**Comment by adw3r** [comment]
Thank you for opened issue. I`ll refactor README due to new entrypoint.
